ava-labs/core-extension

README.md

Fixes wrong image URLs in the README

docs: wrong image urls

---

.github/workflows/e2e_testing.yaml
docs/03-Storage.md

This contains no functional changes, merely updates a few repository urls to reflect the name change

fix: repository urls

---

.github/workflows/e2e_testing.yaml

ci: fix e2e runner name

---

src/background/services/balances/models.ts
src/utils/ipsfResolverWithFallback.ts

https://ava-labs.atlassian.net/browse/CP-8932
Updating our IPFS url hostname from `https://cloudflare-ipfs.com` -> `https://ipfs.io` ahead of the switchover on August 14th per: https://blog.cloudflare.com/cloudflares-public-ipfs-gateways-and-supporting-interplanetary-shipyard
There are no functional changes, a smoke test should be performed to ensure assets such as token images load as expected

chore: update ipfs hostname

---

src/background/services/bridge/handlers/avalanche_bridgeAsset.test.ts
src/background/services/bridge/handlers/avalanche_bridgeAsset.ts

* https://ava-labs.atlassian.net/browse/CP-9080
Fixes missing `nonce`, `maxFeePerGas` and `maxPriorityFeePerGas` props when `avalanche_bridgeAsset` is called.
Perform BTC.b -> BTC bridge via Core Web

fix: bridging BTC.b -> BTC via Core Web

---

src/components/settings/pages/Feedback.tsx

* [CP-9192](https://ava-labs.atlassian.net/browse/CP-9192)
* Just a link update
* Test that the link works

chore: update the feedback link

---

src/background/services/storage/schemaMigrations/migrations/balances_v3.test.ts
src/background/services/storage/schemaMigrations/migrations/balances_v3.ts
src/background/services/storage/schemaMigrations/schemaMap.ts

* https://ava-labs.atlassian.net/browse/CP-9226

chore: remove MATIC from balance cache

---

src/contexts/BridgeProvider.test.tsx
src/contexts/BridgeProvider.tsx
src/pages/Bridge/hooks/useEthBridge.ts

One more fix for bridging ETH to Avalanche

fix: eth to avalanche bridging

---

src/background/services/actions/ActionsService.ts
src/pages/ApproveAction/components/DeviceApproval.tsx

* Never throw when trying to get info for the ledger approval overlay (worst case scenario, we won't show any details, but still prompt for approval)
* `await` the approval/rejection
* Perform an EVM transaction with a Ledger wallet

fix: ledger EVM issues

---

package.json
yarn.lock

Updates `@avalabs/bridge-unified` to v4.0.1
Sanity check on the bridge

chore: upgrade @avalabs/bridge-unified

---

src/contexts/UnifiedBridgeProvider.test.tsx
src/contexts/UnifiedBridgeProvider.tsx
src/hooks/useTokensWithBalances.ts
src/pages/ManageTokens/AddToken.tsx
src/pages/ManageTokens/ManageTokensList.tsx

* [CP-9861](https://ava-labs.atlassian.net/browse/CP-9861)
* Stops ignoring the token data returned by `TokenManager` :)
* Filters hidden tokens from token lists on Send/Swap/Bridge (overridable)
* Fixes the EVM signer for Unified Bridge (it was ignoring `value` prop on the transaction payload)
* Add a custom token, e.g. (`0x13b1f0579bc895b2ffb835f295fd9b63fef36da0`) (you should succeed)
* Hide a token (with balance) on the `Manage Tokens` list and then make sure it's not visible on Send/Swap/Bridge.

fix: token visibility

---

src/background/connections/models.ts
src/background/services/network/utils/getSyncDomain.ts

chore: whitelist redesign app

---

src/pages/Home/components/Portfolio/NetworkWidget/XchainActiveNetworkWidgetContent.tsx

It was broken for a while. We were looking at the wrong spot 👀 

fix: x-chain balance card

---

src/pages/Home/components/Portfolio/NetworkWidget/Assetlist.tsx

fix: weird balances

---

src/hooks/useLanguages.ts

fix: turkish on turkish

---

.github/workflows/create_release.yaml
.github/workflows/e2e_testing.yaml
.github/workflows/main_branch.yaml

Add missing env variable to CI workflows.

fix: add gasless url to ci

---

src/components/settings/components/ContactForm.tsx
src/components/settings/components/ContactInfo.tsx
src/components/settings/components/ContactProfile.tsx

https://ava-labs.atlassian.net/browse/CP-10090
Fix XP address displaying on the contact detail page.
- Show XP address if present
- Change order to show avalanche fields above BTC

fix: xp address in contact book CP-10090

---

src/background/runtime/BackgroundRuntime.ts

- enable the extension, confirm the offscreen connects correctly (`⚡️ connection: Offscreen Connection Provider` log)
- stop the service worker (`chrome://serviceworker-internals/`)
- open the extension popup to trigger the service worker to restart, confirm the offscreen connects correctly again (same log)

fix: close offscreen

---

src/localization/locales/en/translation.json
src/pages/Swap/Swap.tsx
src/pages/Swap/components/TransactionDetails.tsx
src/pages/Swap/utils/index.tsx

Sets minimum slippage for Swaps to 0.1%

fix: set minimum slippage

---

src/contexts/SwapProvider/SwapProvider.test.tsx
src/utils/getExplorerAddress.ts

* Respect the `pathname` coming from `network.explorerUrl`

fix: explorer URLs

---

src/background/services/network/NetworkService.ts
src/background/services/wallet/WalletService.ts
src/background/services/wallet/handlers/avalanche_sendTransaction.test.ts
src/background/services/wallet/handlers/avalanche_sendTransaction.ts
src/utils/network/getProviderForNetwork.ts

Use CoreEth network and wallet for signing Import / Export transactions on C chain.
- Test all wallet types with IMPORT and EXPORT transactions on X AND P AND C chains.
- Test avalanche transactions with all wallet types
- Test avalanche transactions on P and X chains

fix: c-chain import export CP-10256

---

src/contexts/utils/getCurrencyFormatter.test.ts
src/contexts/utils/getCurrencyFormatter.ts

fix: three decimals

---

src/contexts/NetworkFeeProvider.tsx
src/pages/Collectibles/SendEVMCollectible.tsx

[https://ava-labs.atlassian.net/browse/CP-10098](https://ava-labs.atlassian.net/browse/CP-10098)
Remove the check from the provider.
Try the gasless out on different networks
https://github.com/user-attachments/assets/e55c797d-a426-4b85-b399-e02f7cba0d71

fix: remove the check from provider

---

src/pages/Swap/Swap.tsx

[CP-10233](https://ava-labs.atlassian.net/browse/CP-10233)
Filtering the To token in Swap.
Go to swap -> check the From selected token should not appear in the To tokens list.
https://github.com/user-attachments/assets/c9a44202-9d73-473c-b21e-17dcd7a2c1e2

feat: CP-10233 filter toToken list

---

src/components/settings/components/ContactProfile.tsx
src/pages/Send/components/AddressDropdownListItem.tsx

* Have a contact with Solana & X/P address
* Make sure all addresses show in the address book
* Make sure the addresses are aligned in the address book on send screen (when trying to send to the contact)
Missing Solana address in contact details view
| Before | After |
| ------ | ----- |
| ![image](https://github.com/user-attachments/assets/2ff21fcb-741d-4156-8477-26eec66cdbf6) | ![image](https://github.com/user-attachments/assets/4cdeb438-beed-482c-a966-9d04d950832c) |
Alignment issues fixed
| Before    | After |
| -------- | ------- |
| ![image](https://github.com/user-attachments/assets/91e5a053-948e-431d-99bb-84f223f2aa86)  | 
|

fix: solana address fixes

---

src/background/connections/extensionConnection/models.ts
src/background/connections/extensionConnection/registry.ts
src/background/services/firebase/FirebaseService.ts
src/background/services/firebase/handlers/setModel.ts
src/contexts/FirebaseProvider.tsx
src/pages/Home/components/Portfolio/Prompt/Prompt.tsx
src/pages/Home/components/Portfolio/Prompt/models.ts

When the user change the active account or network it does not update the AI Model as well so it can stuck in a previous state.
Set the config before the user's message will be sent.
Go to AI Prompt -> ask to change e.g. the active account -> ask what is the active account
https://github.com/user-attachments/assets/ce867016-b953-406e-bbb1-06896646e8b3

feat: set model config

---

src/pages/Collectibles/components/CollectibleMedia.tsx

[https://ava-labs.atlassian.net/browse/CP-10279](url)
Modify the z-index.
Go to collectibles and check the chip wont overlay.

fix: CP-10279 z-index for chip

---

src/pages/Bridge/components/BridgeForm.tsx

Bridge error has not been cleared after the amount changed.
Set the error to empty.
Go to bridge -> try out with a greater amount then you have -> after try an appropriate amount -> the error should be disappeared 
https://github.com/user-attachments/assets/4b201add-e1aa-4140-a1ab-0e9c574274ac

fix: CP-10102 reset error message

---

.github/workflows/create_release.yaml
.github/workflows/e2e_testing.yaml
.github/workflows/main_branch.yaml

chore: add NOTIFICATION_SENDER_SERVICE_URL to ci

---

src/pages/Permissions/Permissions.tsx

[https://ava-labs.atlassian.net/browse/CP-10585](url)
Change the label.
Try to connect to a dApp and check the label of the button

fix: button label

---

src/pages/ApproveAction/UpdateContacts.tsx
src/pages/Wallet/RenameAccount.tsx
src/pages/Wallet/RenameWallet.tsx
src/pages/Wallet/SwitchAccount.tsx

fix: change button labels

---

src/pages/Home/components/Portfolio/Prompt/Prompt.tsx
src/pages/Home/components/Portfolio/Prompt/models.ts

Improve the AI capabilities to add the changing active network feature.
Introduce the function.
Go to the AI -> try to change an existing network -> after try to change to an imaginary one
https://github.com/user-attachments/assets/ccf5c8ba-977f-4004-9475-5fbcfe379a94

feat: CP-10582 switch network

---

apps/next/src/components/BrandName/BrandName.tsx
apps/next/src/components/BrandName/index.ts
apps/next/src/pages/LockScreen/LockScreen.tsx
apps/next/src/pages/LockScreen/index.ts
packages/ui/src/contexts/AnalyticsProvider/AnalyticsProvider.tsx
packages/ui/src/hooks/useAppDimensions.ts

I was requested to create a PR for even the smallest change, as evidence of the correct setup of my local environment.
The PR contains 4 simple changes:
- creates the placeholder for Lock Screen component [CP-10577]
- implements BrandName component which role is to display Core logo
- updates the props type of AnalyticsProvider component to improve type safety of children property
- refactors the useAppDimensions hook to use constant dimension objects and avoid memory pollution with the continuous object recreation 
The PR introduces no functional changes to the app, hence 

Bartosz's First PR

---

src/utils/getExplorerAddress.ts

Updates explorer url to routescan from etherscan
- TX links on ethereum and ethereum testnet work.
- All TX links in tooltips and activity page point to routescan

chore: update explorer url for ethereum

---

src/contexts/SwapProvider/useEvmSwap.test.tsx
src/contexts/SwapProvider/useEvmSwap.tsx

* [CP-10674](https://ava-labs.atlassian.net/browse/CP-10674)
We were not taking fees into account when calculating min. and max. amount for given slippage.

fix: swap fees & slippage

---

src/contexts/FirebaseProvider.tsx

[Ai legal copy changes ](https://ava-labs.atlassian.net/jira/software/c/projects/CP/boards/72?selectedIssue=CP-10766)
Go to AI -> check the first messages from AI

feat: add new legal copy

---

.releaserc.js
build-scripts/zipscript.mjs
package.json

chore: zip naming for release

---

apps/legacy/rsbuild.legacy.alpha.ts
apps/legacy/rsbuild.legacy.prod.ts
apps/next/rsbuild.next.alpha.ts
apps/next/rsbuild.next.prod.ts

fix: env var replacement

---

packages/types/src/ui-connection.ts
yarn.lock

AvaCloud team needs new domains to be whitelisted to activate testnet mode.
Added domains
[In the ticket.](https://ava-labs.atlassian.net/browse/CP-11369)
https://github.com/user-attachments/assets/9604a870-8e5c-4e60-9aa8-97e7a84b2c46

feat: CP-11369 add new domains to the list

---

packages/service-worker/src/services/seedless/SeedlessWallet.test.ts
packages/service-worker/src/services/seedless/SeedlessWallet.ts

* [CP-10384](https://ava-labs.atlassian.net/browse/CP-10384)
Fixes EIP-191 signing for seedless wallets
Follow the steps from the ticket.
Essentially, you should be able to connect the wallet and accept terms on https://opensea.io/ when onboarded with a seedless account.

fix: seedless eip191 signing

---

apps/next/src/pages/Onboarding/common-screens/CustomizeCore/assets/index.ts
apps/next/src/pages/Onboarding/common-screens/EnjoyYourWalletScreen.tsx
apps/next/src/popup/app.tsx
packages/service-worker/src/runtime/BackgroundRuntime.ts

- Track navigation history only for Popup and Side Panel modes
- Fixes the initial open after the onboarding to accordingly to the selected mode.
- Adds the side panel permission check to Background Runtime initialize function

[Next-Gen] Sidebar followups

---

packages/ui/src/contexts/FeatureFlagsProvider/FeatureFlagsProvider.tsx
packages/ui/src/contexts/LedgerProvider/LedgerProvider.tsx

fix: providers tree

---

packages/service-worker/src/services/featureFlags/utils/getFeatureFlags.test.ts
packages/service-worker/src/services/featureFlags/utils/getFeatureFlags.ts

always add distinct id to ph request

---

apps/next/src/components/CollapsedTokenAmount.tsx
apps/next/src/pages/Approve/components/ActionDetails/ActionDetails.tsx
apps/next/src/pages/Approve/components/ActionDetails/solana/SolanaActionDetails.tsx
apps/next/src/pages/Approve/components/ActionDetails/solana/index.ts
apps/next/src/pages/Approve/hooks/useGasless.ts
packages/types/src/network.ts

* [CP-11861](https://ava-labs.atlassian.net/browse/CP-11861)
* Adds an approval screen for Solana transactions
* Do a Solana transaction - swap or send
https://github.com/user-attachments/assets/5523a425-a4d6-4867-8bef-09f4c85f9ba3

feat(ng): approval screen for Solana transactions
