ava-labs/core-extension

src/pages/Send/components/ContactInput.tsx
Described in: https://ava-labs.atlassian.net/browse/CP-8970
Simply trims input within the `<ContactInput />` TextField. This brings it in parity with how the address input on core.app behaves. 
1. Following the steps in the issue, attempt to prepend a newline to the input, then paste an address
2. Confirm the newline is trimmed and no Unknown or other errors occur
3. See the send form on core.app for comparison
=> fix: handle newlines in address input

.github/workflows/e2e_testing.yaml
The E2E smoke tests need to have the extension key added to the manifest file so that the extension ID is the expected ID after building. The local storage snapshots set at the beginning of tests need this to work properly (set testnet/mainnet, set active network etc).
✅  ~~**NOTE: Needs `EXTENSION_PUBLIC_KEY` to be added as a secret to this repo for this to work. Please let me know if the secret already exists and is named something else.**~~
Adds command in e2e CI flow to add extension public key to manifest file after building extension
This command currently works across all regression and smoke CI workflows in the test automation repo. Same command is being used here.
=> fix: add extension key to e2e ci workflow so snapshots work

src/components/settings/components/ContactForm.tsx
Description in: https://ava-labs.atlassian.net/browse/CP-8558
This implements the suggested solution in the linked issue by removing the X/P- address prefixes when pasting an address in to the new contact form
Confirm by following the Steps to Reproduce in the issue and ensure that X/P- chain addresses are sanitized when pasting in to the X/P- address field in the new contact form. Ensure there is no sanitization upon manual entry
https://github.com/user-attachments/assets/0a6ed5e4-f3b9-48b9-9bc3-acd822b07000
=> fix: improve pasting p/x address in contact form

src/pages/Send/hooks/useSend/useAVMSend.ts, src/pages/Send/hooks/useSend/useBTCSend.ts, src/pages/Send/hooks/useSend/usePVMSend.ts, src/utils/errors/errorHelpers.ts
_no ticket_
Issue found by @blockqa:
https://github.com/user-attachments/assets/2cbe6518-fc31-4a96-bbd7-3a35a0e49a81
* Fixes error in error handling 😅 where we try to call `.startsWith()` on `error.message` which may not be present.
* Awaits `eth_sendTransaction` / `bitcoin_sendTransaction` / `avalanche_sendTransaction` calls so the loading state is properly displayed on send screen (otherwise it's set to `true` and then immediately back to `false` which does not disable the button)
=> fix: await tx broadcast requests

manifest/manifest.json
Gets rid of the error being reported every time extension boots up:
https://github.com/user-attachments/assets/3fd5b4b0-9b46-4310-a913-66f94023618d
☝️ This should be no more. Also fixes `Alt+Shift+B` shortcut I never used ¯\\\_(ツ)_/¯ 
* Updates `manifest.json` to use the proper command name: `_execute_action` instead of `_execute_browser_action`:
* [Reference](https://developer.chrome.com/docs/extensions/reference/api/commands#action_commands)
=> fix: alt+shift+b shortcut

src/background/services/network/NetworkService.test.ts, src/background/services/network/NetworkService.ts, src/background/services/network/handlers/avalanche_setDeveloperMode.ts, src/background/services/network/handlers/saveCustomNetwork.ts, src/background/services/network/handlers/setActiveNetwork.ts, src/background/services/network/handlers/setDeveloperMode.ts, src/background/services/network/handlers/wallet_addEthereumChain.test.ts, src/background/services/network/handlers/wallet_addEthereumChain.ts, src/background/services/network/handlers/wallet_switchEthereumChain.ts, src/background/services/onboarding/finalizeOnboarding.ts
* [CP-9154](https://ava-labs.atlassian.net/browse/CP-9154)
* When network is already supported by the extension, do not use the request's payload, but rather resolve the network object via `NetworkService` and use that instead.
1. Open extension, switch to C-Chain, go to Send
2. Connect to Core Web
3. Switch to Bitcoin _**via Core Web**_
4. Open extension again, you should not see `Unknown error`
https://github.com/user-attachments/assets/e8f54b13-4318-47ec-abf0-f49eaaf2e601
https://github.com/user-attachments/assets/685504c9-72c0-4fe7-b124-b0e0f24ba267
=> fix: treat BTC as known network

src/background/services/bridge/handlers/avalanche_bridgeAsset.test.ts, src/background/services/bridge/handlers/avalanche_bridgeAsset.ts, src/pages/ApproveAction/BridgeTransferAsset.tsx
* Needed to update how we look for the bridged asset for `avalanche_bridgeAsset` handler.
=> fix: bridge initiated from core web

src/background/services/accounts/handlers/avalanche_getAddressesInRange.test.ts, src/background/services/accounts/handlers/avalanche_getAddressesInRange.ts, src/background/services/network/utils/getSyncDomain.ts, src/utils/canSkipApproval.ts
AvaCloud users have to approve the expose addresses transaction after browser refreshing
AvaCloud has been added to the whitelist besides Core web
Go to avacloud -> try to reproduce the ticket description [CP-9331](https://ava-labs.atlassian.net/jira/software/c/projects/CP/boards/72?selectedIssue=CP-9331)
=> fix: CP-9331 add avacloud to whitelist

src/pages/Networks/AddNetwork.tsx
Some padding issues in the Add Network page.
Fixed X Axis paddings
Go to the ADd network page and it should look like as the Edit Network (spacing wise).
=> fix: CP-9334 add network page padding

src/background/services/accounts/handlers/avalanche_getAddressesInRange.test.ts, src/background/services/accounts/handlers/avalanche_getAddressesInRange.ts, src/utils/canSkipApproval.ts
Fix for `Expose addresses?` popup showing up randomly on core.app.
It seems core.app is polling for accounts and reacting to accounts being created/renamed in the extension. If core.app is not the active tab, we show up the approval window.
=> fix: getAddresses popup appearing randomly on core.app

src/background/services/network/utils/getSyncDomain.ts
No ticket. Core Web devs are getting spammed with `Expose Addresses?` prompts when working on `localhost`. This change makes `localhost` whitelisted + makes it behave the same as `core.app` (it will sync the active network between local `Core Web` and Core Extension, sync account names after renaming, etc.)
=> fix: make localhost a synced domain

src/background/services/secrets/SecretsService.test.ts, src/background/services/secrets/SecretsService.ts, src/background/services/wallet/WalletService.test.ts, src/background/services/wallet/WalletService.ts, src/background/services/wallet/handlers/getBtcWalletPolicyDetails.ts, src/contexts/LedgerProvider.tsx
* [CP-9365](https://ava-labs.atlassian.net/browse/CP-9365)
Two issues fixed:
* the `account` parameter for `SecretsService.getBtcWalletPolicyDetails` method was optional, and we were not providing it in some cases, resulting in the method returning `undefined` (UI did not know the policy was already stored)
* `LedgerProvider` was spamming the device with requests, because some functions were not memoized (they were changing, causing `useEffect()` to run and query the device for `masterFingerprint`). Those requests sometimes coincided with actual sign requests, causing them to fail with `Action was already pending on the device` error
* Onboard with Ledger
* Sign a BTC transaction (you should be prompted to store the BTC policy)
* Sign another BTC transaction from the same account (you …
=> fix: ledger btc policy issues

src/background/services/balances/BalancePollingService.ts, src/contexts/SettingsProvider.tsx, src/pages/Collectibles/Collectibles.tsx, src/pages/Collectibles/components/CollectibleMedia.tsx, src/pages/Home/components/Portfolio/Portfolio.tsx, src/pages/ManageCollectibles/ManageCollectiblesList.tsx
_no ticket, fixes for issues found during blue build testing (+ some additional quirks)_
* the weird UI issue where ERC-1155 balances would show up bunched together before the images load
* toggling visibility of NFTs (previously we would toggle based on NFT's `address` only, but it's possible to have multiple NFTs of the same address but different `tokenId` -- this resulted in hiding entire batches of NFTs when trying to hide a specific NFT)
* the Collectibles tab appearing in grid view for a fraction of a second even if the user switched to list view (extension takes a moment to load the preferred state from storage)
Go to the Collectibles tab and play around
=> fix: collectibles view quirks

src/contexts/BalancesProvider.tsx, src/pages/Accounts/AddWalletWithSeedPhrase.tsx, src/pages/Accounts/components/AccountItem.tsx, src/pages/ApproveAction/hooks/useFeeCustomizer.tsx, src/pages/ImportPrivateKey/ImportPrivateKey.tsx, src/pages/Permissions/components/AccountsDropdown.tsx
Fix for https://ava-labs.atlassian.net/browse/AVC-3671
* Renamed `updateBalancesForAllNetworks` to `updateBalancesForNetworks` and added an optional parameter that the backend handler already supported
* Added a call to this method on the approval screen to make sure we get the balances of the transaction's chain even when it's not active/favorited in the extension UI.
* Have Bitcoin (or other - non-Fuji-C-Chain - network as active in the UI)
* Open service worker devtools
* Perform an `eth_sendTransaction` in the playground
* Observe dev tools and ensure we call `/balances:getNative` endpoint for C-Chain Fuji
=> fix: fetch gas token balance on approval screen

src/pages/Ledger/hooks/useRegisterBtcWalletPolicy.ts
* We would show the BTC policy prompt when user was switching AWAY from the Ledger account, because `activeAccount` was being updated, but `walletDetails.type` was still reporting `"ledger"`. We would then go ahead and try to fetch the policy for a non-Ledger account.
* With this change, we'll wait for `activeAccount` and `walletDetails` to be in sync, ensuring it only runs when user switches to Ledger accounts (which don't have the policy registered yet).
* Onboard with Ledger
* Import seed phrase
* Switch to the Ledger account
* Connect Ledger device & go to the Bitcoin app
* You should be prompted for BTC policy
* Switch to the seed phrase account
* You should not be prompted for BTC policy
=> fix: extraneous btc policy prompt

src/pages/Send/components/SendAVM.tsx, src/pages/Send/components/SendPVM.tsx, src/pages/Send/hooks/useIdentifyAddress.ts, src/pages/Send/hooks/useSend/useAVMSend.ts, src/pages/Send/hooks/useSend/usePVMSend.ts, src/pages/Send/utils/correctAddressByPrefix.test.ts, src/pages/Send/utils/correctAddressByPrefix.ts, src/utils/isAddressValid.test.ts, src/utils/isAddressValid.ts
We don't want to completely control the contact input anymore. 
Let the user changes the address to any value.
Go to send on X or P chain -> try to change the address -> it hould let you set an empty string or whatever you want meanwhile it validates correctly.
https://github.com/user-attachments/assets/67504f22-8190-4d1e-bd88-1e8edf29964c
=> fix: CP-9311 x and p send set address

src/background/vmModules/ApprovalController.test.ts, src/background/vmModules/ApprovalController.ts, src/pages/Bridge/components/BridgeForm.tsx, src/pages/SignTransaction/components/SpendLimitInfo/TokenSpendLimit.tsx
Fixes these issues:
* https://ava-labs.atlassian.net/browse/CP-9451
* https://ava-labs.atlassian.net/browse/CP-9452
* https://ava-labs.atlassian.net/browse/CP-9453
=> fix: keystone approvals, bridge amount too low, spend approval dollar value

src/pages/Accounts/components/AccountName.tsx
- Updates `AccountName` component to have a data-testid that was removed with the account name rework causing automation failures
=> fix: add back account name data-testid

src/hooks/usePageHistory.ts, src/pages/Bridge/Bridge.tsx, src/pages/Collectibles/Collectibles.tsx, src/pages/Home/components/Portfolio/Portfolio.tsx, src/pages/Swap/Swap.tsx, src/pages/Swap/hooks/useSwapStateFunctions.ts
We want to add default tokens to the Swap page
Set the AVAX and USDC tokens as default transaction pairs.
Go to the swap page -> you should see the AVAX in the `from` and the USDC in the `to` field -> swap should work as before
https://github.com/user-attachments/assets/0cc4998b-7627-4284-ad56-e807c69cd9ba
=> feat: add default tokens to swap

src/hooks/useTokenPriceIsMissing.ts
For the missing price warning, we look at all the tokens, even those with `balance: 0n`. We also take into consideration the tokens that the user has hidden.
This provides a way to fix the price warning, which right now is visible basically all the time right now.
* If you get the missing price warning, hide the spam/testing tokens or tokens which don't have a price.
https://github.com/user-attachments/assets/45b77ab5-12f1-45cf-8c39-e6299515f766
=> fix: price warning always visible

src/background/connections/middlewares/PermissionMiddleware.ts
Opens up avalanche methods to allow external developers and dApps to interact with the P and X chains. 
It exposes:
- `avalanche_sendTransaction`. When user signs the transaction, it is sent immediately. Prompts the user with an approval window.
- `avalanche_signTransaction`. Signs the transaction and returns the signed transaction to the caller.  Prompts the user with an approval window.
- `avalanche_signMessage`. Sign messages using the X/P derivation path. Can be used to prove owneship of the account simiar to how `personal_sign` works for eth. Prompts the user with an approval window.
- `avalanche_getAccountPubKey`. Returns the the current account's evm and pvm public keys.
Change Core only method list.
Attempt to call the above mentioned RPC methods from a non Core and non localhost …
=> feat: open up avalanche methods CP-9587

jest.config.js, src/contexts/SwapProvider/SwapProvider.test.tsx, src/contexts/SwapProvider/SwapProvider.tsx
Adds response content checks to detect API errors on the Paraswap API.
Add schema validation on the buildTx response
- Make sure swaps still work
- Mock the API response to trigger the error checks.
=> feat: add response check for Paraswap API

src/components/common/BNInput.tsx, src/pages/Send/components/ContactSelect.tsx
* [CP-9544](https://ava-labs.atlassian.net/browse/CP-9544)
* Uses `bigIntToString()` to avoid the rounding mechanism of `TokenUnit` (78c9a7947)
* Fixes some console warnings about `key`s being identical (2947da8c784848ab4befec1834d8d3901695a4ba)
* Go to Send on an EVM network (i.e. C-Chain)
* Choose any address and a token that has lots of decimal places in the balance (token list rounds it up, so beware - see attached video)
* Click `Max` - you should not see an `Unknown Error`
https://github.com/user-attachments/assets/08844674-6ec4-4ce4-b6cc-c0864595f9db
https://github.com/user-attachments/assets/410fb69e-729a-4dc0-86b0-6f2c9de24267
=> fix: max button using rounded up value

src/components/common/BNInput.tsx
_N/A_
* We were calling `stringToBigint(...)` on an empty string
* Go to Swap and enter an amount, it should not crash
=> fix: provide default value to convert

src/pages/Accounts/components/WalletContainer.tsx
* Since Core Web's UTXO Manager will display UTXOs only for the active wallet, we should display the `View P-Chain Details` link only for the active wallet as well.
https://github.com/user-attachments/assets/2b1c2cf9-5a2e-4331-a02a-dfc091048509
=> fix: only show P-Chain Details link for active wallet

src/pages/Send/components/SendForm.tsx
Fixes a UI bug found during regression testing of the latest blue.
1. Have many accounts/contacts
2. Open Send -> click the contact icon
3. Verify the dropdown is of proper size
https://github.com/user-attachments/assets/4fc44d3f-11b6-437e-bbe7-0e2b600f9d61
https://github.com/user-attachments/assets/46155f47-fc91-4662-947d-72eda9b588fc
=> fix: contact dropdown size

src/pages/Accounts/components/AccountItem.tsx, src/pages/Accounts/components/AccountName.tsx
* [CP-9683](https://ava-labs.atlassian.net/browse/CP-9683)
* Brings back the copy address button to the account switcher.
* Use the address copy button and make sure it works
* Bonus points for verifying the captured event names
=> feat: bring back address copy button

src/pages/Accounts/AccountDetailsView.tsx, src/pages/Accounts/Accounts.tsx, src/pages/Accounts/components/AccountItem.tsx, src/pages/Accounts/components/AccountName.tsx, src/pages/Accounts/components/RenameDialog.tsx, src/pages/Accounts/components/WalletHeader.tsx
- Adds `data-testids` to some UI elements in account management flow.
=> chore: add data-testids to account mgmt UI

src/pages/ApproveAction/GenericApprovalScreen.tsx
* [CP-9520](https://ava-labs.atlassian.net/browse/CP-9520)
* We were prompting opening a Ledger app based on the extension's active network when `GenericApprovalScreen` was being used. Now that dApps can connect to different networks without impacting Extension's active network, this stopped working properly.
* With this change, we pass the transaction network to the `useLedgerDisconnectedDialog(...)` hook which will be able to derive the correct app to be opened.
* Connect Ledger and make it your active wallet in extension
* Open Avalanche app on Ledger
* Enable testnet mode & go to [the playground app](https://ava-labs.github.io/extension-avalanche-playground/)
* Switch Extension's network to Bitcoin Testnet
* In the playground app, go to `RPC Calls` and choose `eth_sendTransaction`
* …
=> fix: prompting invalid ledger app

.github/workflows/create_release.yaml, .github/workflows/e2e_testing.yaml, .github/workflows/main_branch.yaml, .github/workflows/pr-checks.yaml
Removes unnecessary .npmrc creation form the workflows. The extension should be buildable by the community. By removing the .npmrc file with the NPM_TOKEN we can ensure that no private npm packages are used in the app.
Removes .npmrc creation from the github workflows
- all CIs are passing
=> chore: remove .npmrc from workflows

src/contexts/utils/getCurrencyFormatter.ts, src/utils/calculateGasAndFees.ts
Due to the lower gas prices we show the user $0.00 as a fee amount which is not correct (maybe itt will in the future).
DIsplay more digits (up to 6)
Go to send or an other tx -> populate everiything and go to the approval screen -> check the fee amount in currency at the bottom of the approval screen
=> feat:CP-9655 handle more digits in fee usd value

.github/workflows/e2e_testing.yaml
- It appears that any time automation tests are kicked off with an extension file larger than approximately ~37mb, it causes problems loading the extension into the browser at the start of the tests. Removing the two largest files before running the tests fixes.
=> fix(ext): remove large ext files causing errors in smoke tests

src/pages/Collectibles/SendEVMCollectible.tsx
Ticket: https://ava-labs.atlassian.net/browse/CP-9816
- Fixes a UI bug found during regression testing of the latest blue. Applied @meeh0w's same exact fix for the send token contact dropdown to the collectible form which had the same issue. Previous fix here: https://github.com/ava-labs/core-extension/pull/107
- Have many accounts/contacts
- Click on the collectibles tab
- Select a collectible to send
- Click contacts button in address input
- Verify the dropdown is of proper size
Before (Blue build) vs After video (Dev build):
https://github.com/user-attachments/assets/cb5f731f-bad7-4fbe-b0f9-eec1e4a2bfe9
=> fix: collectible contact dropdown size

src/contexts/utils/getCurrencyFormatter.test.ts, src/contexts/utils/getCurrencyFormatter.ts
The fraction number display was not the AC.
If the fraction has zeros the first non-zero value will be displayed (when the integer is 0, otherwise we will show two digits).
Go the the portfolio and a transaction (e.g. send) and see the value has the right fraction numbers.
=> feat: CP-9655 check the fraction numebr and transform

src/pages/Accounts/components/AccountItem.tsx
[https://ava-labs.atlassian.net/jira/software/c/projects/CP/boards/72?selectedIssue=CP-9842](url)
Check the active account and scroll there. When the page has been loaded first time we don't need an animation for scrolling.
Go to the account page and play around the accounts a bit. Select a new one to be the active, add another, go back to the portfolio and visit the accounts page again etc.
https://github.com/user-attachments/assets/bf10795f-1ea3-4137-af44-4c5111ef0044
=> feat: scroll to the active account

.github/workflows/e2e_testing.yaml
- Any time automation tests are kicked off with an extension file larger than approximately ~37mb, it causes problems loading the extension into the browser at the start of the tests. Removing the more large files in the CI extension build before running the tests fixes.
=> fix: remove more files to fix ci automation

src/pages/Home/components/Portfolio/Assets.tsx, src/pages/Wallet/TokenFlow.tsx
[https://ava-labs.atlassian.net/browse/CP-9871](url)
Add `useLiveBalance` to two new pages 
Go to Send in the core web app -> send something -> the balance changes should appear in the Assets and Token pages as well not just in Portfolio
https://github.com/user-attachments/assets/f53a8e1e-af4c-4c94-995c-af0c6e33a4f1
=> feat: add balance polling to two other pages

src/contexts/SwapProvider/SwapProvider.test.tsx, src/contexts/SwapProvider/SwapProvider.tsx, src/pages/Swap/Swap.tsx, src/pages/Swap/components/SwapPendingToast.tsx
[https://ava-labs.atlassian.net/browse/CP-9247](url)
Move the toasters to the swap provider to handle the notifications.
Go to swap -> approve a transaction and watch the toasters, it should be pending after the failed ir success message
https://github.com/user-attachments/assets/55d1866f-0c25-41ea-92f5-762be99cdd96
=> feat: CP-9247 add toast to swap status

src/background/services/accounts/AccountsService.ts, src/background/services/network/NetworkService.ts, src/background/services/network/utils/isAvalanchePchainNetwork.ts, src/background/services/network/utils/isAvalancheXchainNetwork.ts, src/background/services/wallet/handlers/avalanche_sendTransaction.ts, src/background/services/wallet/handlers/avalanche_signTransaction.ts, src/utils/caipConversion.ts, src/utils/isDevnet.ts, src/utils/network/getProviderForNetwork.ts
_no ticket_
Platform team deprecated the P-Chain Etna devnet, we can remove the references from our codebase now.
Everything works as before.
=> chore: remove devnet p-chain references

src/contexts/SwapProvider/SwapProvider.test.tsx, src/contexts/SwapProvider/SwapProvider.tsx
_no ticket_
* Maps `srcToken` / `destToken` from `AVAX` to Ether address (`0xEeeEeeeEe....`). It seems Paraswap changed how they interpret it -- or it's been broken for months on our end now. ¯\\\_(ツ)_/¯ 
* Attempt to swap AVAX -> WAVAX. It should work, and the exchange rate should be ~`1:1`
=> fix: swapping AVAX/wAVAX

src/pages/ManageTokens/AddToken.tsx
* [CP-9948](https://ava-labs.atlassian.net/browse/CP-9948)
* Error state was not being reset after successfully fetching the ERC-20's data
Add a custom token (e.g. Willy - `0x403b78f9f817a55b66030c7b2ddab063d28c2c0c`), but type it by hand.
=> fix: reset error state when erc20 data is fetched

src/background/services/balances/BalancePollingService.test.ts, src/background/services/balances/BalancePollingService.ts
* [CP-9902](https://ava-labs.atlassian.net/browse/CP-9902)
* If extension was closed while one of the balance requests was still in-flight, polling would not stop.
* Add an additional indicator when polling is requested and stopped.
* See the videos attached. Timing is key.
https://github.com/user-attachments/assets/859b82dd-eed8-4444-baf0-bd24c280421b
https://github.com/user-attachments/assets/f49b80a0-cf25-4d71-b958-72ced83e9f34
=> fix: balance polling when closed

src/contexts/WalletProvider.tsx
* [CP-9949](https://ava-labs.atlassian.net/browse/CP-9949)
=> fix: do not require unlocking for wallet selector

src/contexts/NetworkFeeProvider.tsx, src/pages/ApproveAction/GenericApprovalScreen.tsx
We want to turn off gasless feature by default.
Does not turn it on.
Go to an approval screen (c-chain tx) -> the gasless witch should be turned off in the beginning
https://github.com/user-attachments/assets/487926cc-b023-4a1b-93cd-b6e1fd001e7e
=> feat: set gasless turn off by default

src/background/connections/middlewares/PermissionMiddleware.ts, src/background/services/network/handlers/wallet_getEthereumChain.ts
Make `wallet_getEthereumChain` available to non-Core dApps
- go to a dApp and connect your wallet (eg.: [lfj](https://lfj.gg/swap))
- send a `wallet_getEthereumChain` request in the developer console via `await window.ethereum.request({method: 'wallet_getEthereumChain', params: []})`
- confirm that the chan info is returned correctly
=> [CP-10099] make wallet_getEthereumChain public

src/components/common/CustomFees.tsx, src/components/common/header/NetworkSwitcher/NetworkSwitcher.tsx, src/contexts/NetworkFeeProvider.tsx, src/localization/locales/en/translation.json, src/pages/ApproveAction/GenericApprovalScreen.tsx
There are multiple tickets live in this PR.
[CP-10087](https://ava-labs.atlassian.net/browse/CP-10087)
[CP-10089](https://ava-labs.atlassian.net/browse/CP-10089)
[CP-10091](https://ava-labs.atlassian.net/browse/CP-10091)
[CP-10092](https://ava-labs.atlassian.net/browse/CP-10092)
Bring back the eligibility state, we cannot rely only on the phase unfortunately. If we are in a ready or not ready (which means we have not had the solution and challenge hexes) we will need the eligibility because of the asynchronous behaviour of the states.
The Success toast has been removed.
The networks list got a default z-index.
Play through the gasless in multiple networks.
**Overlapping issue:** 
https://github.com/user-attachments/assets/e598197e-76f7-43be-a435-61a116419f4d
**Gasless Feature …
=> fix: eligibility state

src/components/common/CustomFees.tsx
The feature was turned on for a moment despite we turned it off in Posthog 
The UI got a feature flag check as well, although we have a check in the provider which is still required because of the Collectibles sending flow.
Play around send.
https://github.com/user-attachments/assets/d9808353-7add-456b-8bb7-538929ae82aa
=> refactor: add feature flag check to UI

src/components/common/GaslessFee.tsx
The Gasless switch size should be smaller.
Using the small switch size
Go to gasless and turn on and off it to check the switch size
=> fix: switch size

src/pages/Swap/hooks/useSwapStateFunctions.ts
* [CP-10131](https://ava-labs.atlassian.net/browse/CP-10131)
When switching network on the swap screen, it now sets the token pair to native -> USDC.
Previously it would set them to `undefined`, which would trigger a `useEffect` and try to use the values from history:
https://github.com/ava-labs/core-extension/blob/9e92da0308e0cccf30937c8c00d06e9503e9bb5f/src/pages/Swap/hooks/useSwapStateFunctions.ts#L89-L108
It would then also recalculate the from/to values, populate them, which would trigger a change event and another render loop...at least that's my understanding, as it was not 100% reproducible for me and probably depends on some timings/race conditions.
This change seems to fix it, though, as I tried many times and with this fix I could not reproduce it even once anymore.
Follow the …
=> fix: swap render loop

src/background/runtime/BackgroundRuntime.ts
Adds a `Restart` item in the context menu that allows the user to easily restart the extension.
Click and see it restart
=> feat: restart extension via context menu

.releaserc.js
With Solana dApp provider, there are now 2 places where `semantic-release` must replace the `CORE_EXTENSION_VERSION` string.
`Release Main Branch` build must pass. [It failed recently](https://github.com/ava-labs/core-extension/actions/runs/14107156962/job/39516243362).
=> fix: version replacement count

src/components/common/CustomFees.tsx, src/components/common/CustomGasSettings.tsx, src/components/common/TruncateFeeAmount.tsx, src/contexts/utils/getCurrencyFormatter.test.ts, src/contexts/utils/getCurrencyFormatter.ts
Handle the small numbers differently because we are having the Fortuna upgrade soon.
Modifications for the gas widget (amount are gone, custom behaviours differently the cog icon has gone)
A component which truncates the numbers and the getCurrencyFormatter modifications.
Go to send -> play around on main and on Fuji as well.
**Mainnet:**
https://github.com/user-attachments/assets/f2970595-2722-4ab5-9ebd-87e223ade79c
**Fuji:**
https://github.com/user-attachments/assets/4ad84948-bd54-4cb5-a2fc-56b52c7f6945
=> feat: CP-10042 gas widget

src/contexts/utils/getCurrencyFormatter.ts, src/pages/Wallet/components/History/components/ActivityCard/ActivityCard.tsx, src/pages/Wallet/components/History/components/ActivityCard/ActivityCardAmount.tsx
The porfolio page had broken prices.
Fix the portfolio and improve the activity page which contained a lot of small numbers
Go to the portfolio page -> go to the activity page and check the prices, gas amounts etc.
=> fix: CP-10042 display amounts

package.json, yarn.lock
Bumps `@avalabs/bridge-unified` to v4.0.2, which updates some warden URLs.
=> chore: update @avalabs/bridge-unified to v4.0.2

src/components/common/CustomGasSettings.tsx, src/components/common/TruncateFeeAmount.tsx
[CP-10042](https://ava-labs.atlassian.net/browse/CP-10042)
Comments
Let one more character to display.
Only show the integer when the fraction has only zero values.
Max Base Fee input formatting.
Go to send or other tx -> click the custom button on the fee widget -> check the values
=> fix: CP-10042 remove scientific, fraction if only zeros, 1 more digit

src/background/services/wallet/handlers/eth_sendTransaction/utils/getTargetNetworkForTx.test.ts, src/background/services/wallet/handlers/eth_sendTransaction/utils/getTargetNetworkForTx.ts
[CP-10056](https://ava-labs.atlassian.net/browse/CP-10056)
Check the chainId besides the caipId.
Go to a custom network and try it out -> you can modify the condition around here: https://vscode.dev/github/ava-labs/core-extension/blob/feat/CP-10056_custom-netowrk-chainid-support/src/background/services/wallet/handlers/eth_sendTransaction/utils/getTargetNetworkForTx.ts#L48
=> feat: CP-10056 allow chainId

src/background/services/wallet/WalletService.test.ts, src/background/services/wallet/WalletService.ts, src/pages/SeedlessPopups/SeedlessAuthPopup.tsx
* Actually finds the correct `publicKey` instead of relying on the `account.index` alone.
* Attempt to sign a few transactions with seedless, using different accounts, possible both C-Chain and P-Chain.
=> fix: seedless signing

src/background/services/wallet/handlers/avalanche_sendTransaction.test.ts, src/background/services/wallet/handlers/avalanche_sendTransaction.ts
* Passes the proper network from `avalanche_sendTransaction` to `WalletService.sign()`. Previously it was always an XP chain and it worked because the legacy `PubKeyType` had both EVM and XP public keys attached. Right now they are separated, so we need to pass the proper network, such that a matching public key is found.
* Perform Cross-Chain Transfer with seedless wallets. **Make sure to do import/exports from and to all chains.**
=> fix: export from C with seedless

src/hooks/useIsFunctionAvailable.ts
When we check for feature availability we should only care about correctly set `activeAccount` and `activeNetwork` when it's actually necessary for the feature.
`isFunctionAvailable` no longer defaults to `false` until `activeAccount` and `activeNetwork` are loaded. If any of them is required for the feature availability check `checkIsFunctionAvailable` will validate them.
- initiate any X/P transaction from Core web (e.g.: cross-chain transfer)
- verify the "This is currently unavailable" warning does not appear
=> [CP-10261] check active account and network only when needed

src/background/services/storage/schemaMigrations/schemaMigrations.test.ts, src/background/services/storage/schemaMigrations/schemaMigrations.ts, src/background/vmModules/ModuleManager.ts, src/utils/caipConversion.ts
* There is an issue reported in Sentry where an old CAIP-2 id for P-Chain is not found. This PR brings back handling of those old CAIP-2 ids. Later I'll prepare a migration to switch the users from old CAIP-2 ids to new ones, as it should've been done in the first place.
* Adds some additional logs to failed migrations error (no data, just schema paths so we at least get some hints as to where the problem is).
-
=> fix: caip lookup + improved sentry reports

src/background/providers/initializeInpageProvider.test.ts, src/background/providers/initializeInpageProvider.ts
Catches potential error when setting `window.ethereum` in the fallback logic
=> fix: catch error on provider fallback mechanism

src/background/services/storage/schemaMigrations/migrations/wallet_v5/commonSchemas.ts, src/background/services/storage/schemaMigrations/migrations/wallet_v5/legacySchema.ts, src/background/services/storage/schemaMigrations/migrations/wallet_v5/newSchema.ts
Fixes [a Sentry-reported issue](https://ava-labs.sentry.io/issues/6509729466/events/b1d11dcb5e1c4d308a95a882df9dffad/?project=6536095) where 3 users are not able to get through the secrets storage migration.
It looses the schema requirements for `importedAccounts` in the secrets storage when migrating from Wallet v4 to v5. This migration does not change anything in the `importedAccounts` model, so we don't really need to validate its contents.
Meanwhile, 3 users are not able to get through this migration because of it.
I was not able to pinpoint the exact cause, all I know is something happened under `importedAccounts` key that made the users' storage out-of-sync with our current schemas.
* Automated tests should still pass.
=> fix: wallet_v5 migration

src/contexts/WalletProvider.tsx
We were attempting to load the wallet details as soon as `<WalletProvider>` was rendered, which also happens on the lock screen.
* Only attempts to load the wallet details after extension gets unlocked.
* Open dev tools
* Lock the extension
* You should not see the `Encryption key missing` error message anymore
=> fix: missing encryption key error

src/background/providers/initializeInpageProvider.test.ts, src/background/providers/initializeInpageProvider.ts
Since Solana support will not be publicly released until it's also supported by Core Mobile, we need to disable the inpage provider (feature flags are not available in the inpage script).
When mobile will be near the release, we can add a feature flag check on the connection screen, but for now let's just not display `Core` as an option on the dapps at all to avoid confusion.
=> fix: disable solana dapp connection

src/components/common/CustomFees.tsx, src/pages/ApproveAction/hooks/useFeeCustomizer.tsx
Set the gas fee modifier to fast on c-chain and Fuji.
e.g. Go to send and check the default modifier value -> try it on other networks
updated: 
https://github.com/user-attachments/assets/ba711c61-75be-4b17-b175-0e4371d64d2c
=> feat:  CP-10438 set default gas fee modifier to fast

src/monitoring/sentryCaptureException.ts, src/pages/Home/components/Portfolio/Prompt/Prompt.tsx
When the AI does not parse the function call correctly (or whatever the reason is) it responds with a status 200 but the text is empty.
Let the user know something happened about the request.
Go to AI -> the way I could see this error when I tried to get my balance with ```balance, token balance etc``` commands, try these
=> fix: handle the error ai does not respond with text but status ok

src/pages/Home/components/Portfolio/Prompt/models.ts
The AI did not care about the amount of a token that the user had and started the swap which caused an error in the background.
Do not let the users to start the swap warn them instead.
Go to AI -> try to swap a token with an amount you don't have
https://github.com/user-attachments/assets/599bdc0f-5a4d-4d15-86f2-9922985e5dbd
=> feat: CP-10558 function param declaration

src/background/services/settings/SettingsService.ts
We want to turn on the Core Assistant by default.
It is on now when the user has no settings.
Reset wallet -> do the onboarding -> check the core assistant is on by default in the settings
=> fix: assistant default state on

src/pages/Home/components/Portfolio/Prompt/Prompt.tsx, src/pages/Home/components/Portfolio/Prompt/models.ts
We want to open urls from AI
Create new chrome tabs.
**NOTE: the reopening is not working for me at the moment. I have checked with the adding a new wallet with ledger and it won't work there neither. I guess the chrome is broken or modified something maybe? So I would kep the function call in the callback anyway.**
Go to AI -> ask for open traderjoe or lfj or any other dApp -> check the buy as well it should open the core.app/buy
https://github.com/user-attachments/assets/d077f6e2-720c-4192-9c44-c1a6d964bdad
=> feat: CP-10608 && CP-10611 add open urls for open a dApp or buy a token

src/background/services/firebase/FirebaseService.ts, src/background/services/firebase/handlers/sendMessage.ts, src/background/services/firebase/models.ts, src/contexts/FirebaseProvider.tsx, src/pages/Home/components/Portfolio/Prompt/Prompt.tsx, src/pages/Home/components/Portfolio/Prompt/models.ts
The AI can lose the context of the chat dialog.
Improve the chat capabilities e.g. the user can continuously write commands and refer back to another command.
Go to AI -> try to chat with it, give a command in pieces (e.g. what do you want after that the amount the token etc.)
https://github.com/user-attachments/assets/a015f1c7-19b0-444c-a3a4-b8bfaa0a6ef9
=> feat: CP-10617 attach chat history to content creation

src/contexts/SwapProvider/ABI_WAVAX.json, src/contexts/SwapProvider/ABI_WETH.json, src/contexts/SwapProvider/SwapProvider.tsx, src/contexts/SwapProvider/constants.ts, src/contexts/SwapProvider/models.ts, src/contexts/SwapProvider/swap-utils.ts, src/contexts/SwapProvider/useEvmSwap.test.tsx, src/contexts/SwapProvider/useEvmSwap.tsx, src/contexts/SwapProvider/useSolanaSwap.tsx, src/pages/Swap/Swap.tsx, src/pages/Swap/components/TransactionDetails.tsx, src/pages/Swap/utils/calculateRate.ts, src/pages/Swap/utils/index.tsx
_(copy of https://github.com/ava-labs/core-extension/pull/263, targetting `main`)_
* [CP-10281](https://ava-labs.atlassian.net/browse/CP-10281)
* When swapping between AVAX <-> WAVAX or ETH <-> WETH, perform `deposit` or `withdraw` transactions directly on their respective contracts instead of going through Velora (Paraswap)
* Swap between AVAX and WAVAX
* Same for ETH <-> WETH
* "Powered by..." notice should be hidden
* Info about fees should be hidden
* Transactions should NOT go through Velora (Paraswap)
https://github.com/user-attachments/assets/052d3b1d-198d-4376-8650-c0ebae014ae1
=> feat: internally wrap/unwrap WAVAX & WETH

.github/workflows/create_release.yaml, .github/workflows/e2e_testing.yaml, .github/workflows/main_branch.yaml, .github/workflows/pr-checks-nextgen.yml, .github/workflows/pr-checks.yaml
RSBuild reads the `.env` files a bit different than webpack did, if it encounters a `#` character it stops.
This line:
```bash
echo SEEDLESS_ORG_ID={{ secrets.SEEDLESS_ORG_ID }} >> .env.production
```
results in this line in the file:
```.env
SEEDLESS_ORG_ID=Org#1234
```
RSBuild when parsing the file, stops with the `#` character, whereas webpack would have read the whole line.
Encapsulating the whole `echo` in quotes ensures the lines in the env file looks like this:
```.env
SEEDLESS_ORG_ID="Org#1234"
```
which lets the RSBuild read the proper values.
=> fix: enquote env file building

packages/messaging/src/serialization/deserialize.test.ts, packages/messaging/src/serialization/deserialize.ts, packages/messaging/src/serialization/serialize.test.ts, packages/messaging/src/serialization/serialize.ts
With the repo restructuring, I was also updating the ts config, which resulted in typescript catching more errors than before (in some places it complained about us passing `Buffer` instead of `Uint8Array`).
So I fixed that and some values previously sent as `Buffer` between UI and the service worker are now sent as `Uint8Array`, but we didn't have a serializer for it.
This PR adds the serializer.
1. Use an existing seedless account with a FIDO key configured (Yubikey / Passkey)
2. Attempt to perform any action that requires MFA: change recovery methods or initiate seedphrase export.
3. If you can confirm it with your FIDO key, it works 🎉
=> fix: serializer for Uint8Array

packages/common/src/utils/caipConversion.ts
* We currently map known _fake_ chain IDs (like the ones we have for Bitcoin or X/P chains) to proper CAIP-2 ids (e.g. `eip155:4503599627370475` -> `bip122:000000000019d6689c085ae165831e93`). This was missing for Solana chains.
=> fix: resolve Solana fake chain ids to CAIP-2 ids

packages/common/src/utils/getCoreWebUrl.test.ts, packages/common/src/utils/getCoreWebUrl.ts
There is a new URL in Core web, instead of `/address` they use `/portfolio` (it is cheating though they redirect the old `/address` requests to `/portfolio`..)
Set the new URL and remove the network GET param which is not used to anything from now.
go to settings -> check the Core Web link on the top of the list
https://github.com/user-attachments/assets/1645cdef-f14d-41bc-ac5a-b28c1b019200
=> feat: CP-11567 set new portfolio url and remove network param

packages/common/src/utils/index.ts, packages/common/src/utils/retry.test.ts, packages/common/src/utils/retry.ts, packages/ui/src/contexts/SwapProvider/useEvmSwap.tsx
This replicates the logic introduced in the EVM Module for fetching the transaction receipt.
From my testing, it speeds up the appearance of the "success" toast by ~2s. Not great, but it's a start.
Sanity check on the swap feature.
=> perf: try to lower the confirmation delay for swap

apps/next/src/pages/Onboarding/flows/SeedlessFlow/SeedlessFlow.tsx
Ticket: https://ava-labs.atlassian.net/browse/CP-11884
When onboarding with seedless, customize core page was skipped.
Changed the path in onNext. 
Please onboard using seedless and once you fill out the wallet details, hitting next should take you to the customize core page and not the select avatar page
https://github.com/user-attachments/assets/b2b3e360-51f4-4d83-925b-5c0cf80797b0
=> fix(seedless): seedless skipped customize core page

packages/ui/src/contexts/SwapProvider/SwapProvider.tsx, packages/ui/src/contexts/SwapProvider/swap-utils.ts
This PR updates the swap logic to remove the application of slippage on the quoted amountOut values.
Currently, we’re displaying “min amount out” by applying the slippage to the quoted output, which leads to users seeing worse rates compared to competitors — even when our quotes are actually better. This fix ensures the actual quoted amount is displayed, aligning our UI with user expectations and improving rate clarity.
- Removed slippage adjustment from amountOut calculations
- Now displaying the raw amountOut returned by the quote API
=> fix(swaps): remove slippage from displayed amountOut

packages/ui/src/contexts/SwapProvider/SwapProvider.tsx
No ticket
There was a bug where we handled setting the swap network. 
And it was ignoring the network change. 
Please test getting a quotes in one network, then switch the network and try to get the quotes again. 
https://github.com/user-attachments/assets/1d440444-b45f-4e45-ad5b-fffe446e30ab
=> fix(swap): fix setting swap network
